name: vi_gcd_env
channels:
  - conda-forge
  - pytorch
  - pyg
  - defaults
dependencies:
  - python=3.9
  - jupyter
  - numpy
  - pandas
  - scikit-learn
  - scikit-learn-extra
  - matplotlib
  - scikit-image
  - scipy
  - pytorch::pytorch 
  - pytorch::cpuonly    
  - pyg
  - pyg::pytorch-scatter
  - pyg::pytorch-sparse
  - pyg::pytorch-cluster
  - pyg::pytorch-spline-conv

